</div>
</div>
</div>

<div id="leftcolumn">
<div class="innertube">
<?php
include("topmenu.php");
?>
</div>
</div>


<div id="footer">
<hr class="text-only" />
This site is
generated by <a href="http://github.com/sylvainhalle/FantasticWindmill">Fantastic Windmill</a>.
</div>

</div>

<?php include ("template_code.php"); ?>

</body>
</html>
